### ISSUE TITLE
zooming has become broken

### ISSUE THREAD

**Issue by LifeIsStrange** [damiendevienne/Lifemap#1]
Hi @damiendevienne The tree of life truly is my favorite website on the internet, it is a revolutionnary tool for discovering and visualizing knowledge.
Unfortunately, on desktop (chrome) the zooming has become "broken", it is janky/stuttery. (circles appears where they shouldn't, movement has a variable speed and is terribly slow, etc)
I would extremely appreciate if you could fix this regression as this website has a unique value and makes the world a better place.

**Comment by damiendevienne** [comment]
hello @LifeIsStrange, 
Can you please tell me what url you are referring to? I cannot see the bug here. 
Or simply tell me if it is fixed (the server may have had an issue at the moment you tried, and it is maybe solved?)

**Comment by LifeIsStrange** [comment]
Hi @damiendevienne I must have missed the notification at the time, sry for the delay, so yeah basically the issue is fixed.
Although about the transparent circles that connect the graph edges on each zoom they quickly disappear and then reappear which is slighly flickery unlike the other svg forms that continuously scale without disappearing/reapearing, I wonder if this is a regression, but anyway no big deal and not the original issue, thx :)
